name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Specify which branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies (Frontend)
        run: npm install
        working-directory: frontend  # Run npm install in the frontend folder

      - name: Build project
        run: npm run build
        working-directory: frontend  # Run npm run build in the frontend folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: frontend  # Make sure deploy uses the frontend folder
